[AGIEval]
data_path=data/AGIEval/data/v1
prompt_path=data/AGIEval/data/few_shot_prompts.csv
;[ARC]
;data_path=""
;prompt_path=""
;[BBH]
;data_path=""
;prompt_path=""
;[ceval]
;data_path=""
;prompt_path=""
;[CLUE]
;data_path=""
;prompt_path=""
;[cmmlu]
;data_path=""
;prompt_path=""
;[commonsenseqa]
;data_path=""
;prompt_path=""
;[drop]
;data_path=""
;prompt_path=""
;[FewCLUE]
;data_path=""
;prompt_path=""
;[flores_first100]
;data_path=""
;prompt_path=""
;[GAOKAO-BENCH]
;data_path=""
;prompt_path=""
;[gsm8k]
;data_path=""
;prompt_path=""
;[hellaswag]
;data_path=""
;prompt_path=""
;[humaneval]
;data_path=""
;prompt_path=""
;[lambada]
;data_path=""
;prompt_path=""
;[LCSTS]
;data_path=""
;prompt_path=""
;[math]
;data_path=""
;prompt_path=""
;[mbpp]
;data_path=""
;prompt_path=""
;[mmlu]
;data_path=""
;prompt_path=""
;[nq]
;data_path=""
;prompt_path=""
;[openbookqa]
;data_path=""
;prompt_path=""
;[piqa]
;data_path=""
;prompt_path=""
;[race]
;data_path=""
;prompt_path=""
;[siqa]
;data_path=""
;prompt_path=""
;[strategyqa]
;data_path=""
;prompt_path=""
;[summedits]
;data_path=""
;prompt_path=""
;[SuperGLUE]
;data_path=""
;prompt_path=""
;[TheoremQA]
;data_path=""
;prompt_path=""
;[triviaqa]
;data_path=""
;prompt_path=""
;[tydiqa]
;data_path=""
;prompt_path=""
;[winogrande]
;data_path=""
;prompt_path=""
;[xstory_cloze]
;data_path=""
;prompt_path=""
;[Xsum]
;data_path=""
;prompt_path=""